# Generated by Django 4.2.10 on 2025-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.IntegerField(unique=True)),
                ('photo', models.ImageField(upload_to='project_photos/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('view_more_link', models.URLField(blank=True)),
            ],
        ),
    ]
