# Generated by Django 4.2.10 on 2025-04-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact_delete_blogpost_delete_project_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('photo', models.ImageField(upload_to='project_photos/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
