# Generated by Django 4.2.10 on 2025-04-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
